<?php

namespace Tests;

use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function assertClassUsesTraits($trait, $class)
    {
        $this->assertArrayHasKey(
            $trait,
            class_uses($class),
            "{$class} class must use {$trait} trait");
    }


    protected function assertDontBroadcastToCurrentUser($event, $socketId = 'socket_id')
    {
        $this->assertInstanceOf(ShouldBroadcast::class, $event);

        $this->assertEquals(
            $socketId, //Generated by Broadcast::shouldReceive('socket')->andReturn('socket_id');
            $event->socket,
            'The event' . get_class($event) . ' must call the method "dontBroadcastToCurrentUser" in the constructor.');
    }

    protected function assertEventChannelType($channelType, $event)
    {
        $type = [
            'public' => \Illuminate\Broadcasting\Channel::class,
            'private' => \Illuminate\Broadcasting\PrivateChannel::class,
            'presence' => \Illuminate\Broadcasting\PresenceChannel::class,
        ];
        $this->assertEquals($type[$channelType], get_class($event->broadcastOn()));

    }

    protected function assertEventChannelName($channelName, $event)
    {
        $this->assertEquals($channelName, $event->broadcastOn()->name);
    }
}
